"use client";

import { pdfjs } from "react-pdf";
import "./globals";
import "./globals.css";

import { UserProvider } from "@/contexts/UserContext";
import { HomeHeader } from "./HomeHeader";
import { ThemeProvider } from "@/contexts/ThemeContext";

import { Toaster } from "@/components/ui/sonner";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

pdfjs.GlobalWorkerOptions.workerSrc = `//unpkg.com/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.js`;
const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => (
  <html lang="en" className="w-full h-full box-border">
    <UserProvider>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <body className="w-full h-full box-border">
          <HomeHeader />
          {children}
          <Toaster />
        </body>
      </ThemeProvider>
    </UserProvider>
  </html>
);

export default RootLayout;
