"use client";

import { pdfjs } from "react-pdf";
import "./globals";
import "./globals.css";

import { UserProvider } from "@/contexts/UserContext";
import { HomeHeader } from "./HomeHeader";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

pdfjs.GlobalWorkerOptions.workerSrc = `//unpkg.com/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.js`;
const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => (
  <UserProvider>
    <html lang="en" className="w-full h-full box-border">
      <body className="w-full h-full box-border">
        <HomeHeader />
        {children}
      </body>
    </html>
  </UserProvider>
);

export default RootLayout;
